import {
  Checkpoint,
  Dindi,
  Camp,
  WaterTanker,
  Volunteer,
  MedicalStation,
  SanitationCrew,
  Alert,
  OperationalEvent,
  SimulationState,
} from "./types";

export const INITIAL_CHECKPOINTS: Checkpoint[] = [
  {
    id: "CP-01",
    shortCode: "CP1",
    name: "Pune Swargate Junction",
    lat: 18.5018,
    lng: 73.8636,
    currentDensity: 45,
    maxCapacity: 15000,
    currentCount: 6750,
    trendRate10Min: 2,
    forecast45Min: 48,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 560,
    weatherStatus: "Clear 28°C",
    incomingDindis: ["Dindi #3"],
    assignedVolunteers: 8,
    bypassRouteAvailable: false,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 45, label: "Current" },
      { minute: 15, density: 46, label: "+15m" },
      { minute: 30, density: 47, label: "+30m" },
      { minute: 45, density: 48, label: "+45m" },
    ],
  },
  {
    id: "CP-02",
    shortCode: "CP2",
    name: "Hadapsar Gadital Chowk",
    lat: 18.5089,
    lng: 73.926,
    currentDensity: 62,
    maxCapacity: 12000,
    currentCount: 7440,
    trendRate10Min: 5,
    forecast45Min: 68,
    risk: "ATTENTION",
    status: "WARNING",
    elevationMeters: 575,
    weatherStatus: "Overcast 27°C",
    incomingDindis: ["Dindi #7"],
    assignedVolunteers: 6,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 62, label: "Current" },
      { minute: 15, density: 64, label: "+15m" },
      { minute: 30, density: 66, label: "+30m" },
      { minute: 45, density: 68, label: "+45m" },
    ],
  },
  {
    id: "CP-03",
    shortCode: "CP3",
    name: "Dive Ghat Base (Wadki)",
    lat: 18.441,
    lng: 73.968,
    currentDensity: 78,
    maxCapacity: 10000,
    currentCount: 7800,
    trendRate10Min: 9,
    forecast45Min: 86,
    risk: "HIGH",
    status: "WARNING",
    elevationMeters: 620,
    weatherStatus: "Light Rain 24°C",
    incomingDindis: ["Dindi #14"],
    assignedVolunteers: 10,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 78, label: "Current" },
      { minute: 15, density: 81, label: "+15m" },
      { minute: 30, density: 84, label: "+30m" },
      { minute: 45, density: 86, label: "+45m" },
    ],
  },
  {
    id: "CP-04",
    shortCode: "CP4",
    name: "Dive Ghat Apex (Palkhi Point)",
    lat: 18.412,
    lng: 74.004,
    currentDensity: 91,
    maxCapacity: 10000,
    currentCount: 9100,
    trendRate10Min: 18,
    forecast45Min: 97,
    risk: "CRITICAL",
    status: "CRITICAL",
    elevationMeters: 840,
    weatherStatus: "Rain 18mm/h, Fog",
    incomingDindis: ["Dindi #14", "Dindi #7"],
    assignedVolunteers: 5,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 91, label: "Current" },
      { minute: 15, density: 93, label: "+15m" },
      { minute: 30, density: 95, label: "+30m" },
      { minute: 45, density: 97, label: "+45m" },
    ],
  },
  {
    id: "CP-05",
    shortCode: "CP5",
    name: "Saswad Palkhi Maidan North",
    lat: 18.343,
    lng: 74.031,
    currentDensity: 88,
    maxCapacity: 20000,
    currentCount: 17600,
    trendRate10Min: 12,
    forecast45Min: 93,
    risk: "HIGH",
    status: "WARNING",
    elevationMeters: 690,
    weatherStatus: "Moderate Rain 23°C",
    incomingDindis: ["Dindi #1"],
    assignedVolunteers: 12,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 88, label: "Current" },
      { minute: 15, density: 90, label: "+15m" },
      { minute: 30, density: 92, label: "+30m" },
      { minute: 45, density: 93, label: "+45m" },
    ],
  },
  {
    id: "CP-06",
    shortCode: "CP6",
    name: "Jejuri Khandoba Foothills",
    lat: 18.278,
    lng: 74.156,
    currentDensity: 52,
    maxCapacity: 25000,
    currentCount: 13000,
    trendRate10Min: 4,
    forecast45Min: 56,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 710,
    weatherStatus: "Passing Clouds 26°C",
    incomingDindis: ["Dindi #9"],
    assignedVolunteers: 8,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 52, label: "Current" },
      { minute: 15, density: 53, label: "+15m" },
      { minute: 30, density: 55, label: "+30m" },
      { minute: 45, density: 56, label: "+45m" },
    ],
  },
  {
    id: "CP-07",
    shortCode: "CP7",
    name: "Lonand Rail-Road Junction",
    lat: 18.046,
    lng: 74.188,
    currentDensity: 40,
    maxCapacity: 15000,
    currentCount: 6000,
    trendRate10Min: 1,
    forecast45Min: 42,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 610,
    weatherStatus: "Partly Cloudy 29°C",
    incomingDindis: ["Dindi #11"],
    assignedVolunteers: 6,
    bypassRouteAvailable: false,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 40, label: "Current" },
      { minute: 15, density: 41, label: "+15m" },
      { minute: 30, density: 41, label: "+30m" },
      { minute: 45, density: 42, label: "+45m" },
    ],
  },
  {
    id: "CP-08",
    shortCode: "CP8",
    name: "Taradgaon Pilgrim Transit",
    lat: 17.989,
    lng: 74.312,
    currentDensity: 34,
    maxCapacity: 12000,
    currentCount: 4080,
    trendRate10Min: 2,
    forecast45Min: 36,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 580,
    weatherStatus: "Sunny 30°C",
    incomingDindis: ["Dindi #5"],
    assignedVolunteers: 4,
    bypassRouteAvailable: false,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 34, label: "Current" },
      { minute: 15, density: 35, label: "+15m" },
      { minute: 30, density: 35, label: "+30m" },
      { minute: 45, density: 36, label: "+45m" },
    ],
  },
  {
    id: "CP-09",
    shortCode: "CP9",
    name: "Phaltan Agricultural Yard",
    lat: 17.985,
    lng: 74.433,
    currentDensity: 48,
    maxCapacity: 30000,
    currentCount: 14400,
    trendRate10Min: 3,
    forecast45Min: 51,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 570,
    weatherStatus: "Sunny 31°C",
    incomingDindis: ["Dindi #18"],
    assignedVolunteers: 10,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 48, label: "Current" },
      { minute: 15, density: 49, label: "+15m" },
      { minute: 30, density: 50, label: "+30m" },
      { minute: 45, density: 51, label: "+45m" },
    ],
  },
  {
    id: "CP-10",
    shortCode: "CP10",
    name: "Malshiras Rural Cross",
    lat: 17.842,
    lng: 74.912,
    currentDensity: 25,
    maxCapacity: 15000,
    currentCount: 3750,
    trendRate10Min: 1,
    forecast45Min: 27,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 540,
    weatherStatus: "Clear 32°C",
    incomingDindis: ["Dindi #22"],
    assignedVolunteers: 4,
    bypassRouteAvailable: false,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 25, label: "Current" },
      { minute: 15, density: 25, label: "+15m" },
      { minute: 30, density: 26, label: "+30m" },
      { minute: 45, density: 27, label: "+45m" },
    ],
  },
  {
    id: "CP-11",
    shortCode: "CP11",
    name: "Velapur High Grounds",
    lat: 17.745,
    lng: 75.12,
    currentDensity: 30,
    maxCapacity: 20000,
    currentCount: 6000,
    trendRate10Min: 2,
    forecast45Min: 32,
    risk: "NORMAL",
    status: "NORMAL",
    elevationMeters: 510,
    weatherStatus: "Clear 32°C",
    incomingDindis: ["Dindi #25"],
    assignedVolunteers: 5,
    bypassRouteAvailable: false,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 30, label: "Current" },
      { minute: 15, density: 31, label: "+15m" },
      { minute: 30, density: 31, label: "+30m" },
      { minute: 45, density: 32, label: "+45m" },
    ],
  },
  {
    id: "CP-12",
    shortCode: "CP12",
    name: "Pandharpur Chandrabhaga Ghat",
    lat: 17.678,
    lng: 75.327,
    currentDensity: 65,
    maxCapacity: 60000,
    currentCount: 39000,
    trendRate10Min: 6,
    forecast45Min: 72,
    risk: "ATTENTION",
    status: "NORMAL",
    elevationMeters: 460,
    weatherStatus: "Warm 33°C",
    incomingDindis: ["Dindi #25"],
    assignedVolunteers: 25,
    bypassRouteAvailable: true,
    bypassActive: false,
    forecastTrajectory: [
      { minute: 0, density: 65, label: "Current" },
      { minute: 15, density: 67, label: "+15m" },
      { minute: 30, density: 70, label: "+30m" },
      { minute: 45, density: 72, label: "+45m" },
    ],
  },
];

export const INITIAL_DINDIS: Dindi[] = [
  {
    id: "DINDI-14",
    number: 14,
    name: "Sant Tukaram Maharaj Sansthan Lead Palkhi",
    leader: "Babasaheb More",
    pilgrimCount: 38000,
    currentSegment: "Dive Ghat Incline (CP3-CP4)",
    currentPaceKmH: 3.2,
    standardPaceKmH: 4.2,
    paceDropPercent: 21,
    etaNextHalt: "13:20",
    nextHalt: "Camp 6 (Saswad)",
    status: "CRITICAL",
    lat: 18.423,
    lng: 73.988,
    weatherDelayMinutes: 28,
    terrainFactor: 1.45,
    rerouted: false,
    routeColor: "#E85A1C",
  },
  {
    id: "DINDI-07",
    number: 7,
    name: "Alandi Youth Bhakt Dindi",
    leader: "Dnyandev Patil",
    pilgrimCount: 24000,
    currentSegment: "Hadapsar to Dive Ghat Base",
    currentPaceKmH: 4.0,
    standardPaceKmH: 4.2,
    paceDropPercent: 5,
    etaNextHalt: "14:15",
    nextHalt: "Camp 6 (Saswad)",
    status: "ATTENTION",
    lat: 18.455,
    lng: 73.955,
    weatherDelayMinutes: 10,
    terrainFactor: 1.1,
    rerouted: false,
    routeColor: "#3B82F6",
  },
  {
    id: "DINDI-03",
    number: 3,
    name: "Mauli Warkari Sangha",
    leader: "Suresh Maharaj Gholap",
    pilgrimCount: 31000,
    currentSegment: "Swargate to Hadapsar",
    currentPaceKmH: 4.3,
    standardPaceKmH: 4.4,
    paceDropPercent: 2,
    etaNextHalt: "15:30",
    nextHalt: "Camp 3 (Dive Ghat Base)",
    status: "NORMAL",
    lat: 18.49,
    lng: 73.93,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#10B981",
  },
  {
    id: "DINDI-01",
    number: 1,
    name: "Sant Dnyaneshwar Palkhi Vanguard",
    leader: "Haribhau Kadam",
    pilgrimCount: 42000,
    currentSegment: "Saswad Palkhi Maidan Exit",
    currentPaceKmH: 4.1,
    standardPaceKmH: 4.2,
    paceDropPercent: 2,
    etaNextHalt: "16:00",
    nextHalt: "Camp 5 (Jejuri)",
    status: "NORMAL",
    lat: 18.36,
    lng: 74.02,
    weatherDelayMinutes: 5,
    terrainFactor: 1.05,
    rerouted: false,
    routeColor: "#8B5CF6",
  },
  {
    id: "DINDI-09",
    number: 9,
    name: "Solapur Gramin Seva Dindi",
    leader: "Pandurang Jadhav",
    pilgrimCount: 19000,
    currentSegment: "Saswad to Jejuri Link",
    currentPaceKmH: 3.8,
    standardPaceKmH: 4.0,
    paceDropPercent: 5,
    etaNextHalt: "17:10",
    nextHalt: "Camp 5 (Jejuri)",
    status: "NORMAL",
    lat: 18.3,
    lng: 74.12,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#EC4899",
  },
  {
    id: "DINDI-11",
    number: 11,
    name: "Baramati Seva Mandal Dindi",
    leader: "Kishor Shinde",
    pilgrimCount: 26000,
    currentSegment: "Lonand Bypass",
    currentPaceKmH: 4.2,
    standardPaceKmH: 4.3,
    paceDropPercent: 2,
    etaNextHalt: "18:00",
    nextHalt: "Camp 7 (Lonand)",
    status: "NORMAL",
    lat: 18.06,
    lng: 74.17,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#14B8A6",
  },
  {
    id: "DINDI-05",
    number: 5,
    name: "Kolhapur Karveer Warkari",
    leader: "Anand Gavali",
    pilgrimCount: 21000,
    currentSegment: "Taradgaon Approach",
    currentPaceKmH: 4.1,
    standardPaceKmH: 4.2,
    paceDropPercent: 2,
    etaNextHalt: "19:00",
    nextHalt: "Camp 8 (Phaltan)",
    status: "NORMAL",
    lat: 17.99,
    lng: 74.3,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#F59E0B",
  },
  {
    id: "DINDI-18",
    number: 18,
    name: "Marathwada Muktai Dindi",
    leader: "Santosh Joshi",
    pilgrimCount: 28000,
    currentSegment: "Phaltan East Highway",
    currentPaceKmH: 4.4,
    standardPaceKmH: 4.4,
    paceDropPercent: 0,
    etaNextHalt: "19:45",
    nextHalt: "Camp 8 (Phaltan)",
    status: "NORMAL",
    lat: 17.98,
    lng: 74.42,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#6366F1",
  },
  {
    id: "DINDI-22",
    number: 22,
    name: "Konkan Vithoba Dindi",
    leader: "Vilas Sawant",
    pilgrimCount: 16000,
    currentSegment: "Malshiras Green Belt",
    currentPaceKmH: 4.0,
    standardPaceKmH: 4.1,
    paceDropPercent: 2,
    etaNextHalt: "20:30",
    nextHalt: "Camp 10 (Malshiras)",
    status: "NORMAL",
    lat: 17.85,
    lng: 74.9,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#10B981",
  },
  {
    id: "DINDI-25",
    number: 25,
    name: "Pandharpur Nagari Pioneer Dindi",
    leader: "Eknath Maharaj",
    pilgrimCount: 35000,
    currentSegment: "Velapur - Shegaon Sector",
    currentPaceKmH: 3.9,
    standardPaceKmH: 4.0,
    paceDropPercent: 3,
    etaNextHalt: "21:15",
    nextHalt: "Camp 12 (Pandharpur)",
    status: "NORMAL",
    lat: 17.69,
    lng: 75.3,
    weatherDelayMinutes: 0,
    terrainFactor: 1.0,
    rerouted: false,
    routeColor: "#F97316",
  },
];

export const INITIAL_CAMPS: Camp[] = [
  {
    id: "CAMP-06",
    name: "Camp 6 (Saswad Palkhi Maidan)",
    capacity: 45000,
    currentOccupancy: 54000,
    occupancyPercent: 120,
    waterStockPercent: 18,
    waterBurnRateLitersPerMin: 420,
    minutesToWaterDepletion: 34,
    assignedTankers: [],
    foodStockPercent: 48,
    shelterStatus: "OVERFLOW",
    lat: 18.344,
    lng: 74.032,
    status: "CRITICAL",
  },
  {
    id: "CAMP-01",
    name: "Camp 1 (Pune Racecourse Staging)",
    capacity: 40000,
    currentOccupancy: 28000,
    occupancyPercent: 70,
    waterStockPercent: 82,
    waterBurnRateLitersPerMin: 180,
    minutesToWaterDepletion: 240,
    assignedTankers: [],
    foodStockPercent: 88,
    shelterStatus: "STABLE",
    lat: 18.502,
    lng: 73.864,
    status: "NORMAL",
  },
  {
    id: "CAMP-02",
    name: "Camp 2 (Hadapsar Transit Yard)",
    capacity: 30000,
    currentOccupancy: 24000,
    occupancyPercent: 80,
    waterStockPercent: 65,
    waterBurnRateLitersPerMin: 220,
    minutesToWaterDepletion: 140,
    assignedTankers: ["T-05"],
    foodStockPercent: 75,
    shelterStatus: "STABLE",
    lat: 18.508,
    lng: 73.927,
    status: "NORMAL",
  },
  {
    id: "CAMP-03",
    name: "Camp 3 (Dive Ghat Foothill Camp)",
    capacity: 25000,
    currentOccupancy: 22500,
    occupancyPercent: 90,
    waterStockPercent: 44,
    waterBurnRateLitersPerMin: 310,
    minutesToWaterDepletion: 62,
    assignedTankers: ["T-01"],
    foodStockPercent: 60,
    shelterStatus: "STABLE",
    lat: 18.442,
    lng: 73.969,
    status: "ATTENTION",
  },
  {
    id: "CAMP-04",
    name: "Camp 4 (Zadache Math Valley)",
    capacity: 20000,
    currentOccupancy: 15000,
    occupancyPercent: 75,
    waterStockPercent: 58,
    waterBurnRateLitersPerMin: 160,
    minutesToWaterDepletion: 180,
    assignedTankers: [],
    foodStockPercent: 82,
    shelterStatus: "STABLE",
    lat: 18.39,
    lng: 74.015,
    status: "NORMAL",
  },
  {
    id: "CAMP-05",
    name: "Camp 5 (Jejuri Palkhi Grounds)",
    capacity: 50000,
    currentOccupancy: 29000,
    occupancyPercent: 58,
    waterStockPercent: 76,
    waterBurnRateLitersPerMin: 250,
    minutesToWaterDepletion: 210,
    assignedTankers: ["T-02"],
    foodStockPercent: 85,
    shelterStatus: "STABLE",
    lat: 18.279,
    lng: 74.157,
    status: "NORMAL",
  },
  {
    id: "CAMP-07",
    name: "Camp 7 (Lonand Agro Center)",
    capacity: 35000,
    currentOccupancy: 14000,
    occupancyPercent: 40,
    waterStockPercent: 90,
    waterBurnRateLitersPerMin: 140,
    minutesToWaterDepletion: 320,
    assignedTankers: [],
    foodStockPercent: 92,
    shelterStatus: "STABLE",
    lat: 18.047,
    lng: 74.189,
    status: "NORMAL",
  },
  {
    id: "CAMP-08",
    name: "Camp 8 (Phaltan Sugar Mill Grounds)",
    capacity: 60000,
    currentOccupancy: 21000,
    occupancyPercent: 35,
    waterStockPercent: 88,
    waterBurnRateLitersPerMin: 190,
    minutesToWaterDepletion: 360,
    assignedTankers: [],
    foodStockPercent: 90,
    shelterStatus: "STABLE",
    lat: 17.986,
    lng: 74.434,
    status: "NORMAL",
  },
];

export const INITIAL_TANKERS: WaterTanker[] = [
  {
    id: "T-03",
    capacityLiters: 12000,
    status: "AVAILABLE",
    currentHub: "Hub 2 (Saswad Bypass)",
    assignedCampId: undefined,
    distanceKm: 1.8,
    etaMinutes: 12,
    driverName: "Ramesh Pawar (Cell: 98221-4401)",
    lat: 18.348,
    lng: 74.022,
  },
  {
    id: "T-01",
    capacityLiters: 15000,
    status: "DISPATCHED",
    currentHub: "Hub 1 (Hadapsar)",
    assignedCampId: "CAMP-03",
    distanceKm: 3.4,
    etaMinutes: 18,
    driverName: "Sanjay Shinde",
    lat: 18.452,
    lng: 73.96,
    targetLat: 18.442,
    targetLng: 73.969,
  },
  {
    id: "T-02",
    capacityLiters: 12000,
    status: "EN_ROUTE",
    currentHub: "Hub 2 (Saswad)",
    assignedCampId: "CAMP-05",
    distanceKm: 6.2,
    etaMinutes: 25,
    driverName: "Vikas Raut",
    lat: 18.31,
    lng: 74.09,
    targetLat: 18.279,
    targetLng: 74.157,
  },
  {
    id: "T-04",
    capacityLiters: 10000,
    status: "AVAILABLE",
    currentHub: "Hub 1 (Hadapsar)",
    assignedCampId: undefined,
    distanceKm: 5.1,
    etaMinutes: 22,
    driverName: "Mahesh Kolhe",
    lat: 18.51,
    lng: 73.93,
  },
  {
    id: "T-05",
    capacityLiters: 12000,
    status: "DISCHARGING",
    currentHub: "Camp 2 Tanker Bay",
    assignedCampId: "CAMP-02",
    distanceKm: 0,
    etaMinutes: 0,
    driverName: "Baban Gaikwad",
    lat: 18.508,
    lng: 73.927,
  },
  {
    id: "T-06",
    capacityLiters: 15000,
    status: "AVAILABLE",
    currentHub: "Hub 3 (Phaltan)",
    assignedCampId: undefined,
    distanceKm: 14.5,
    etaMinutes: 40,
    driverName: "Pravin Jagtap",
    lat: 17.985,
    lng: 74.433,
  },
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: "VOL-101",
    name: "Aniket Deshmukh",
    skills: ["TRAFFIC", "CROWD_CONTROL", "MARATHI_HINDI"],
    locationName: "Dive Ghat Base CP3",
    lat: 18.441,
    lng: 73.968,
    distanceToTargetKm: 2.1,
    batteryPercent: 84,
    status: "AVAILABLE",
    avatarColor: "#E85A1C",
  },
  {
    id: "VOL-102",
    name: "Pooja Kulkarni",
    skills: ["MEDICAL", "MARATHI_HINDI"],
    locationName: "Dive Ghat Apex Post",
    lat: 18.412,
    lng: 74.004,
    distanceToTargetKm: 0.1,
    batteryPercent: 92,
    status: "AVAILABLE",
    avatarColor: "#10B981",
  },
  {
    id: "VOL-103",
    name: "Sachin Thorat",
    skills: ["TRAFFIC", "CROWD_CONTROL"],
    locationName: "Hadapsar Gadital CP2",
    lat: 18.5089,
    lng: 73.926,
    distanceToTargetKm: 6.4,
    batteryPercent: 78,
    status: "AVAILABLE",
    avatarColor: "#3B82F6",
  },
  {
    id: "VOL-104",
    name: "Sneha Bhosale",
    skills: ["MEDICAL", "CROWD_CONTROL"],
    locationName: "Saswad North CP5",
    lat: 18.343,
    lng: 74.031,
    distanceToTargetKm: 4.8,
    batteryPercent: 88,
    status: "AVAILABLE",
    avatarColor: "#8B5CF6",
  },
  {
    id: "VOL-105",
    name: "Rahul Mane",
    skills: ["TRAFFIC", "LOGISTICS"],
    locationName: "Wadki Sector 2",
    lat: 18.43,
    lng: 73.975,
    distanceToTargetKm: 1.8,
    batteryPercent: 65,
    status: "AVAILABLE",
    avatarColor: "#F59E0B",
  },
  {
    id: "VOL-106",
    name: "Meera Dhavale",
    skills: ["TRAFFIC", "MARATHI_HINDI"],
    locationName: "Dive Ghat Incline 4",
    lat: 18.418,
    lng: 73.995,
    distanceToTargetKm: 0.8,
    batteryPercent: 95,
    status: "AVAILABLE",
    avatarColor: "#EC4899",
  },
  {
    id: "VOL-107",
    name: "Tanaji Shinde",
    skills: ["CROWD_CONTROL", "LOGISTICS"],
    locationName: "Saswad Palkhi Maidan",
    lat: 18.344,
    lng: 74.032,
    distanceToTargetKm: 5.2,
    batteryPercent: 71,
    status: "AVAILABLE",
    avatarColor: "#14B8A6",
  },
  {
    id: "VOL-108",
    name: "Aarti Salunkhe",
    skills: ["MEDICAL", "MARATHI_HINDI"],
    locationName: "Jejuri Foothills",
    lat: 18.278,
    lng: 74.156,
    distanceToTargetKm: 16.0,
    batteryPercent: 82,
    status: "AVAILABLE",
    avatarColor: "#10B981",
  },
  {
    id: "VOL-109",
    name: "Ganesh Mohite",
    skills: ["CROWD_CONTROL", "TRAFFIC"],
    locationName: "Dive Ghat Base",
    lat: 18.44,
    lng: 73.97,
    distanceToTargetKm: 2.2,
    batteryPercent: 90,
    status: "AVAILABLE",
    avatarColor: "#E85A1C",
  },
  {
    id: "VOL-110",
    name: "Priyanka Chavan",
    skills: ["MEDICAL", "CROWD_CONTROL", "LOGISTICS"],
    locationName: "Dive Ghat Apex Checkpoint",
    lat: 18.413,
    lng: 74.003,
    distanceToTargetKm: 0.2,
    batteryPercent: 85,
    status: "AVAILABLE",
    avatarColor: "#8B5CF6",
  },
  {
    id: "VOL-111",
    name: "Digambar Joshi",
    skills: ["TRAFFIC", "LOGISTICS"],
    locationName: "Saswad West Gate",
    lat: 18.34,
    lng: 74.025,
    distanceToTargetKm: 5.5,
    batteryPercent: 77,
    status: "AVAILABLE",
    avatarColor: "#3B82F6",
  },
  {
    id: "VOL-112",
    name: "Komal Waghmare",
    skills: ["MEDICAL", "TRAFFIC"],
    locationName: "Dive Ghat Hairpin 3",
    lat: 18.42,
    lng: 73.99,
    distanceToTargetKm: 1.1,
    batteryPercent: 89,
    status: "AVAILABLE",
    avatarColor: "#10B981",
  },
];

export const INITIAL_MEDICAL_STATIONS: MedicalStation[] = [
  {
    id: "MS-02",
    name: "Saswad Rural Health Center & Mobile ICU",
    capacityBeds: 40,
    occupiedBeds: 6,
    occupancyPercent: 15,
    status: "NORMAL",
    doctorCount: 6,
    availableAmbulances: 3,
    heatStrokeKits: 50,
    lat: 18.345,
    lng: 74.033,
  },
  {
    id: "MS-01",
    name: "Pune Sassoon Base Trauma Hub",
    capacityBeds: 100,
    occupiedBeds: 22,
    occupancyPercent: 22,
    status: "NORMAL",
    doctorCount: 14,
    availableAmbulances: 8,
    heatStrokeKits: 120,
    lat: 18.502,
    lng: 73.864,
  },
  {
    id: "MS-03",
    name: "Dive Ghat Apex Rapid Response Post",
    capacityBeds: 15,
    occupiedBeds: 11,
    occupancyPercent: 73,
    status: "SURGE",
    doctorCount: 3,
    availableAmbulances: 2,
    heatStrokeKits: 25,
    lat: 18.412,
    lng: 74.004,
  },
  {
    id: "MS-04",
    name: "Jejuri Primary Health Unit",
    capacityBeds: 30,
    occupiedBeds: 8,
    occupancyPercent: 26,
    status: "NORMAL",
    doctorCount: 4,
    availableAmbulances: 2,
    heatStrokeKits: 40,
    lat: 18.278,
    lng: 74.156,
  },
  {
    id: "MS-05",
    name: "Pandharpur Sub-District Hospital & Trauma Center",
    capacityBeds: 150,
    occupiedBeds: 45,
    occupancyPercent: 30,
    status: "NORMAL",
    doctorCount: 22,
    availableAmbulances: 10,
    heatStrokeKits: 200,
    lat: 17.678,
    lng: 75.327,
  },
];

export const INITIAL_SANITATION_CREWS: SanitationCrew[] = [
  {
    id: "SC-02",
    name: "Cleanup Crew #2 (Dive Ghat Sector)",
    status: "DISPATCHED",
    leadName: "Ganesh Kadam",
    activeToiletsCleaned: 42,
    zone: "Dive Ghat Incline Sector",
    lat: 18.418,
    lng: 73.998,
  },
  {
    id: "SC-01",
    name: "Pune-Hadapsar Waste Squad",
    status: "ON_DUTY",
    leadName: "Nitin Bhalerao",
    activeToiletsCleaned: 110,
    zone: "Hadapsar Gadital",
    lat: 18.508,
    lng: 73.926,
  },
  {
    id: "SC-03",
    name: "Saswad Field Sanitation Unit",
    status: "AVAILABLE",
    leadName: "Sanjay Londhe",
    activeToiletsCleaned: 65,
    zone: "Saswad Palkhi Maidan",
    lat: 18.343,
    lng: 74.031,
  },
  {
    id: "SC-04",
    name: "Jejuri Eco Hygiene Team",
    status: "ON_DUTY",
    leadName: "Amol Gaikwad",
    activeToiletsCleaned: 88,
    zone: "Jejuri Foothills",
    lat: 18.278,
    lng: 74.156,
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: "ALT-401",
    title: "CP4 Dive Ghat Density Surge Imminent",
    location: "Checkpoint 4 — Dive Ghat Apex",
    severity: "CRITICAL",
    cause: "Dindi #14 pace slowdown (3.2 km/h) & rain delay compressing 38k pilgrims",
    forecastText: "Density projected to reach 97% in 43 minutes without bypass intervention",
    recommendedAction: "Reroute Dindi #14 to Bypass Route B + Deploy 5 Volunteers to Apex",
    timestamp: "10:42 AM",
    status: "ACTIVE",
    timeToCriticalMinutes: 43,
    priorityScore: 92,
    scoreBreakdown: {
      density: 35,
      urgency: 25,
      population: 20,
      resource: 12,
    },
  },
  {
    id: "ALT-402",
    title: "Camp 6 Water Stock Depletion Risk",
    location: "Camp 6 — Saswad Palkhi Maidan",
    severity: "HIGH",
    cause: "Occupancy surged to 120% (54k pilgrims); current burn rate 420 L/min",
    forecastText: "Water reserves drop below 10% critical reserve threshold in 34 minutes",
    recommendedAction: "Dispatch Tanker T-03 (12,000L) from Hub 2 and open Backup Shelter B",
    timestamp: "10:39 AM",
    status: "ACTIVE",
    timeToCriticalMinutes: 34,
    priorityScore: 78,
    scoreBreakdown: {
      density: 22,
      urgency: 24,
      population: 18,
      resource: 14,
    },
  },
  {
    id: "ALT-403",
    title: "Dindi #14 Incline Speed Drop",
    location: "Dive Ghat Hairpin Incline (CP3-CP4)",
    severity: "MEDIUM",
    cause: "18mm/h rainfall and slippery 14% slope reduced pace by 21%",
    forecastText: "Arrival at Saswad delayed by +45m; creates compression wave at CP4",
    recommendedAction: "Activate slip-resistant grip gravel squad and traffic marshalling",
    timestamp: "10:35 AM",
    status: "ACTIVE",
    timeToCriticalMinutes: 50,
    priorityScore: 64,
    scoreBreakdown: {
      density: 18,
      urgency: 16,
      population: 18,
      resource: 12,
    },
  },
];

export const INITIAL_EVENTS: OperationalEvent[] = [
  {
    id: "EV-01",
    timestamp: "10:35:12",
    eventType: "DETECTION",
    severity: "INFO",
    source: "Telemetry Radar / Dive Ghat Incline",
    description: "Precipitation radar detected 18mm/h rainfall at Dive Ghat Apex (CP4).",
  },
  {
    id: "EV-02",
    timestamp: "10:37:44",
    eventType: "DETECTION",
    severity: "WARNING",
    source: "Palkhi GPS Telemetry",
    description: "Dindi #14 walking speed dropped from 4.2 km/h to 3.2 km/h (-21% pace drop).",
  },
  {
    id: "EV-03",
    timestamp: "10:39:20",
    eventType: "FORECAST",
    severity: "CRITICAL",
    source: "45-Min Predictive Risk Engine",
    description: "Simulated Forecast: CP4 density will surge from 91% to 97% within 43 minutes.",
    result: "Threshold breach imminent (Cap: 10,000 pilgrims)",
  },
  {
    id: "EV-04",
    timestamp: "10:40:02",
    eventType: "ALERT",
    severity: "CRITICAL",
    source: "Rule & Threshold Alert Engine",
    description: "Generated High-Priority Incident #INC-402 (Priority Score: 92/100).",
  },
  {
    id: "EV-05",
    timestamp: "10:41:15",
    eventType: "COPILOT_REC",
    severity: "INFO",
    source: "AI Operations Copilot",
    description: "Generated multi-agency mitigation plan: Reroute Dindi #14, dispatch Tanker T-03, deploy 5 volunteers.",
  },
];

export const INITIAL_SIMULATION_STATE: SimulationState = {
  isSimulating: true,
  simulationSpeed: 1,
  currentClock: "10:42 AM",
  totalPilgrims: 1240000,
  routeUtilization: 88,
  weatherCondition: {
    rainfallMmH: 18,
    temperatureC: 24,
    heatIndex: "MODERATE",
    activeRainSector: "Dive Ghat Sector (CP3-CP4)",
  },
  checkpoints: INITIAL_CHECKPOINTS,
  dindis: INITIAL_DINDIS,
  camps: INITIAL_CAMPS,
  tankers: INITIAL_TANKERS,
  volunteers: INITIAL_VOLUNTEERS,
  medicalStations: INITIAL_MEDICAL_STATIONS,
  sanitationCrews: INITIAL_SANITATION_CREWS,
  alerts: INITIAL_ALERTS,
  events: INITIAL_EVENTS,
  activeIncidentId: "INC-402",
  decisionStage: "DECIDED",
  isMitigated: false,
  showBeforeAfterModal: false,
  beforeAfterSummary: null,
};

