export interface PalkhiEvent {
  id: string;
  date: string;
  dateRaw: string; // ISO-like for sorting
  locationName: string;
  palkhi: "TUKARAM_MAHARAJ" | "DNYANESHWAR_MAHARAJ";
  description: string;
  highlight?: string;
  isRingan?: boolean;
  ringanType?: string;
  lat: number;
  lng: number;
}

// Complete Authentic 2026 Palkhi Schedules
export const TUKARAM_MAHARAJ_SCHEDULE_2026: PalkhiEvent[] = [
  {
    id: "tuk-01",
    palkhi: "TUKARAM_MAHARAJ",
    date: "11-Jul-2026",
    dateRaw: "2026-07-11",
    locationName: "Dehu (Inamdar Wada)",
    description: "Prasthan (Departure) from Dehu temple, overnight halt at Inamdar Wada.",
    highlight: "Departure & Prasthan Ceremony",
    lat: 18.7185,
    lng: 73.7712,
  },
  {
    id: "tuk-02",
    palkhi: "TUKARAM_MAHARAJ",
    date: "12-Jul-2026",
    dateRaw: "2026-07-12",
    locationName: "Akurdi (Vitthal Mandir)",
    description: "Procession marches through Pimpri-Chinchwad, overnight halt at Akurdi.",
    highlight: "Twin City Welcome",
    lat: 18.6492,
    lng: 73.7707,
  },
  {
    id: "tuk-03",
    palkhi: "TUKARAM_MAHARAJ",
    date: "13-Jul-2026",
    dateRaw: "2026-07-13",
    locationName: "Pune (Nanapeth)",
    description: "Reaches Pune city, grand reception, 2-day halt at Nanapeth (Nivadungya Vithoba).",
    highlight: "Pune Grand Arrival (Nanapeth)",
    lat: 18.5167,
    lng: 73.8667,
  },
  {
    id: "tuk-04",
    palkhi: "TUKARAM_MAHARAJ",
    date: "15-Jul-2026",
    dateRaw: "2026-07-15",
    locationName: "Loni Kalbhor",
    description: "Departs Pune city and proceeds toward Solapur highway, halt at Loni Kalbhor.",
    highlight: "Solapur Corridor Transition",
    lat: 18.4875,
    lng: 74.0203,
  },
  {
    id: "tuk-05",
    palkhi: "TUKARAM_MAHARAJ",
    date: "16-Jul-2026",
    dateRaw: "2026-07-16",
    locationName: "Yavat",
    description: "Halt at Yavat village, evening Kirtan and community prasad.",
    highlight: "Yavat Palkhi Maidan",
    lat: 18.4682,
    lng: 74.2882,
  },
  {
    id: "tuk-06",
    palkhi: "TUKARAM_MAHARAJ",
    date: "17-Jul-2026",
    dateRaw: "2026-07-17",
    locationName: "Varvand",
    description: "Marches through Daund rural sector, overnight halt at Varvand.",
    highlight: "Varvand Lake Camp",
    lat: 18.4239,
    lng: 74.3725,
  },
  {
    id: "tuk-07",
    palkhi: "TUKARAM_MAHARAJ",
    date: "18-Jul-2026",
    dateRaw: "2026-07-18",
    locationName: "Undawadi",
    description: "Overnight camp at Undawadi Palkhi Tal.",
    highlight: "Undawadi Camp",
    lat: 18.2512,
    lng: 74.5218,
  },
  {
    id: "tuk-08",
    palkhi: "TUKARAM_MAHARAJ",
    date: "19-Jul-2026",
    dateRaw: "2026-07-19",
    locationName: "Baramati",
    description: "Procession enters Baramati town, civic reception at Sharda Mandir.",
    highlight: "Baramati Civic Welcome",
    lat: 18.1517,
    lng: 74.5772,
  },
  {
    id: "tuk-09",
    palkhi: "TUKARAM_MAHARAJ",
    date: "20-Jul-2026",
    dateRaw: "2026-07-20",
    locationName: "Katewadi",
    description: "Arrival at Katewadi, traditional Goat & Sheep Ringan (शेळ्या-मेंढ्यांचे रिंगण सोहळा).",
    highlight: "Goat & Sheep Ringan (मेंढ्यांचे रिंगण)",
    isRingan: true,
    ringanType: "Goat & Sheep Ringan (शेळ्या-मेंढ्यांचे रिंगण)",
    lat: 18.1342,
    lng: 74.6541,
  },
  {
    id: "tuk-10",
    palkhi: "TUKARAM_MAHARAJ",
    date: "21-Jul-2026",
    dateRaw: "2026-07-21",
    locationName: "Anthurne",
    description: "Procession stays overnight at Anthurne village.",
    highlight: "Anthurne Camp",
    lat: 18.0621,
    lng: 74.7219,
  },
  {
    id: "tuk-11",
    palkhi: "TUKARAM_MAHARAJ",
    date: "22-Jul-2026",
    dateRaw: "2026-07-22",
    locationName: "Nimgaon Ketki",
    description: "Camp at Nimgaon Ketki, evening Hari Jagar.",
    highlight: "Nimgaon Ketki Ringan ground",
    lat: 18.0125,
    lng: 74.8315,
  },
  {
    id: "tuk-12",
    palkhi: "TUKARAM_MAHARAJ",
    date: "23-Jul-2026",
    dateRaw: "2026-07-23",
    locationName: "Indapur",
    description: "Grand procession halt at Indapur town.",
    highlight: "Indapur Gol Ringan & Halt",
    lat: 18.1154,
    lng: 75.0315,
  },
  {
    id: "tuk-13",
    palkhi: "TUKARAM_MAHARAJ",
    date: "24-Jul-2026",
    dateRaw: "2026-07-24",
    locationName: "Akluj (Mane Vidyalaya Ground)",
    description: "Niravsamadhi and Spectacular Gol Ringan at Akluj with horse races.",
    highlight: "Gol Ringan & Niravsamadhi (गोल रिंगण)",
    isRingan: true,
    ringanType: "Akluj Gol Ringan (अकलूज गोल रिंगण)",
    lat: 17.8864,
    lng: 75.0242,
  },
  {
    id: "tuk-14",
    palkhi: "TUKARAM_MAHARAJ",
    date: "25-Jul-2026",
    dateRaw: "2026-07-25",
    locationName: "Borgaon",
    description: "Halt at Borgaon Palkhi Tal.",
    highlight: "Borgaon Camp",
    lat: 17.8012,
    lng: 75.1415,
  },
  {
    id: "tuk-15",
    palkhi: "TUKARAM_MAHARAJ",
    date: "26-Jul-2026",
    dateRaw: "2026-07-26",
    locationName: "Pirachi Kuroli",
    description: "Ubhya Ringan & overnight stay at Pirachi Kuroli.",
    highlight: "Ubhe Ringan",
    isRingan: true,
    ringanType: "Ubhe Ringan (उभे रिंगण)",
    lat: 17.7512,
    lng: 75.2142,
  },
  {
    id: "tuk-16",
    palkhi: "TUKARAM_MAHARAJ",
    date: "27-Jul-2026",
    dateRaw: "2026-07-27",
    locationName: "Wakhari",
    description: "Grand congregation of both Palkhis at Wakhari. Final major Ringan.",
    highlight: "Wakhari Maha Ringan (वाखरी रिंगण)",
    isRingan: true,
    ringanType: "Maha Ringan (वाखरी महा रिंगण)",
    lat: 17.7125,
    lng: 75.2814,
  },
  {
    id: "tuk-17",
    palkhi: "TUKARAM_MAHARAJ",
    date: "28-Jul-2026",
    dateRaw: "2026-07-28",
    locationName: "Pandharpur",
    description: "Arrival in Pandharpur. Palkhi enters the holy town with victory chants.",
    highlight: "Pandharpur Nagar Pravesh (नगर प्रवेश)",
    lat: 17.6805,
    lng: 75.3308,
  },
  {
    id: "tuk-18",
    palkhi: "TUKARAM_MAHARAJ",
    date: "29-Jul-2026",
    dateRaw: "2026-07-29",
    locationName: "Pandharpur (Chandrabhaga)",
    description: "Holy bath in Chandrabhaga river and Vitthal-Rukmini darshan on Ashadhi Ekadashi.",
    highlight: "Ashadhi Ekadashi Mahapuja (महापूजा)",
    lat: 17.6775,
    lng: 75.3289,
  },
  {
    id: "tuk-19",
    palkhi: "TUKARAM_MAHARAJ",
    date: "02-Aug-2026",
    dateRaw: "2026-08-02",
    locationName: "Pandharpur → Dehu Return",
    description: "Return journey to Dehu begins with Gopalkala ceremony.",
    highlight: "Return Journey (परतीचा प्रवास)",
    lat: 17.6805,
    lng: 75.3308,
  },
];

export const DNYANESHWAR_MAHARAJ_SCHEDULE_2026: PalkhiEvent[] = [
  {
    id: "dny-01",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "12-Jul-2026",
    dateRaw: "2026-07-12",
    locationName: "Alandi (Darshan Mandap)",
    description: "Prasthan ceremony at 8 PM from Alandi Darshan Mandap Building.",
    highlight: "Alandi Prasthan 8:00 PM",
    lat: 18.6774,
    lng: 73.8964,
  },
  {
    id: "dny-02",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "13-Jul-2026 to 14-Jul-2026",
    dateRaw: "2026-07-13",
    locationName: "Pune (Bhavani Peth)",
    description: "Reaches Pune city, 2-day stay and darshan at Bhavani Peth Palkhi Vithoba Mandir.",
    highlight: "Pune City 2-Day Halt",
    lat: 18.5089,
    lng: 73.8712,
  },
  {
    id: "dny-03",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "15-Jul-2026 to 16-Jul-2026",
    dateRaw: "2026-07-15",
    locationName: "Saswad (via Dive Ghat)",
    description: "Iconic procession crosses Dive Ghat mountain pass, 2-day halt at Saswad.",
    highlight: "Dive Ghat Crossing & Saswad 2-Day Halt",
    lat: 18.3437,
    lng: 74.0293,
  },
  {
    id: "dny-04",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "17-Jul-2026",
    dateRaw: "2026-07-17",
    locationName: "Jejuri",
    description: "Procession reaches temple town Jejuri, Bhandara festival and night stay.",
    highlight: "Jejuri Bhandara & Night Halt",
    lat: 18.2753,
    lng: 74.1573,
  },
  {
    id: "dny-05",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "18-Jul-2026",
    dateRaw: "2026-07-18",
    locationName: "Valhe",
    description: "Overnight camp at Valhe village.",
    highlight: "Valhe Camp",
    lat: 18.1562,
    lng: 74.1956,
  },
  {
    id: "dny-06",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "19-Jul-2026",
    dateRaw: "2026-07-19",
    locationName: "Lonand (1 Day Stay)",
    description: "Procession halt at Lonand (Only 1 day stay this year).",
    highlight: "Lonand 1-Day Stay",
    lat: 17.9861,
    lng: 74.2956,
  },
  {
    id: "dny-07",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "20-Jul-2026",
    dateRaw: "2026-07-20",
    locationName: "Taradgaon",
    description: "Overnight halt at Taradgaon village.",
    highlight: "Taradgaon Camp",
    lat: 17.9421,
    lng: 74.3654,
  },
  {
    id: "dny-08",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "21-Jul-2026",
    dateRaw: "2026-07-21",
    locationName: "Phaltan",
    description: "Procession reaches Phaltan, civic welcome and night stay.",
    highlight: "Phaltan City Halt",
    lat: 17.9862,
    lng: 74.4356,
  },
  {
    id: "dny-09",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "22-Jul-2026",
    dateRaw: "2026-07-22",
    locationName: "Barad",
    description: "Halt at Barad village ground.",
    highlight: "Barad Camp",
    lat: 17.9125,
    lng: 74.5842,
  },
  {
    id: "dny-10",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "23-Jul-2026",
    dateRaw: "2026-07-23",
    locationName: "Natepute",
    description: "Procession halts at Natepute, Ringan ground preparation.",
    highlight: "Natepute Camp",
    lat: 17.8543,
    lng: 74.7653,
  },
  {
    id: "dny-11",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "24-Jul-2026",
    dateRaw: "2026-07-24",
    locationName: "Purandawade",
    description: "Overnight stay at Purandawade.",
    highlight: "Purandawade Camp",
    lat: 17.8015,
    lng: 74.8852,
  },
  {
    id: "dny-12",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "25-Jul-2026",
    dateRaw: "2026-07-25",
    locationName: "Barapur",
    description: "Procession stays at Barapur.",
    highlight: "Barapur Camp",
    lat: 17.7562,
    lng: 74.9951,
  },
  {
    id: "dny-13",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "26-Jul-2026",
    dateRaw: "2026-07-26",
    locationName: "Bhandishegaon",
    description: "Halt at Bhandishegaon ground.",
    highlight: "Bhandishegaon Camp",
    lat: 17.7214,
    lng: 75.1254,
  },
  {
    id: "dny-14",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "27-Jul-2026",
    dateRaw: "2026-07-27",
    locationName: "Wakhari",
    description: "Wakhari halt, grand Ringan meeting with Tukaram Maharaj Palkhi.",
    highlight: "Wakhari Maha Ringan (महा रिंगण)",
    isRingan: true,
    ringanType: "Wakhari Maha Ringan",
    lat: 17.7125,
    lng: 75.2814,
  },
  {
    id: "dny-15",
    palkhi: "DNYANESHWAR_MAHARAJ",
    date: "28-Jul-2026",
    dateRaw: "2026-07-28",
    locationName: "Pandharpur (Ashadhi Mahapuja)",
    description: "Arrival at Pandharpur. Grand entry for Ashadhi Ekadashi Mahapuja.",
    highlight: "Pandharpur Arrival & Ashadhi Ekadashi",
    lat: 17.6805,
    lng: 75.3308,
  },
];

export interface PalkhiWaypoint {
  sequence: number;
  location: string;
  lat: number;
  lng: number;
  type: string;
  distance_from_start_km: number;
}

export const SANT_DNYANESHWAR_ROUTE_CONFIG = {
  palkhi_name: "Sant Dnyaneshwar Maharaj Palkhi",
  origin: "Alandi",
  destination: "Pandharpur",
  total_distance_km: 240,
  route_waypoints: [
    {
      sequence: 1,
      location: "Alandi Temple",
      lat: 18.6775,
      lng: 73.8967,
      type: "Start Point / Night Halt",
      distance_from_start_km: 0,
    },
    {
      sequence: 2,
      location: "Vishrantwadi, Pune",
      lat: 18.5630,
      lng: 73.8741,
      type: "Day Break",
      distance_from_start_km: 14,
    },
    {
      sequence: 3,
      location: "Parnakuti, Yerawada",
      lat: 18.5432,
      lng: 73.8821,
      type: "Day Break",
      distance_from_start_km: 18,
    },
    {
      sequence: 4,
      location: "Pune (Bhavani Peth)",
      lat: 18.5135,
      lng: 73.8694,
      type: "Night Halt (2 Days)",
      distance_from_start_km: 22,
    },
    {
      sequence: 5,
      location: "Hadapsar",
      lat: 18.5089,
      lng: 73.9259,
      type: "Day Break",
      distance_from_start_km: 30,
    },
    {
      sequence: 6,
      location: "Dive Ghat Base",
      lat: 18.4358,
      lng: 73.9875,
      type: "Scenic Walk / Steep Climb",
      distance_from_start_km: 40,
    },
    {
      sequence: 7,
      location: "Saswad",
      lat: 18.3428,
      lng: 74.0302,
      type: "Night Halt (2 Days)",
      distance_from_start_km: 53,
    },
    {
      sequence: 8,
      location: "Jejuri",
      lat: 18.2774,
      lng: 74.1582,
      type: "Night Halt",
      distance_from_start_km: 70,
    },
    {
      sequence: 9,
      location: "Valhe",
      lat: 18.1751,
      lng: 74.1610,
      type: "Night Halt",
      distance_from_start_km: 87,
    },
    {
      sequence: 10,
      location: "Lonand",
      lat: 18.0401,
      lng: 74.1884,
      type: "Night Halt",
      distance_from_start_km: 108,
    },
    {
      sequence: 11,
      location: "Chandoba Limba",
      lat: 18.0012,
      lng: 74.2415,
      type: "Standing Ringan",
      distance_from_start_km: 115,
    },
    {
      sequence: 12,
      location: "Taradgaon",
      lat: 17.9621,
      lng: 74.2691,
      type: "Night Halt",
      distance_from_start_km: 124,
    },
    {
      sequence: 13,
      location: "Phaltan",
      lat: 17.9868,
      lng: 74.4326,
      type: "Night Halt",
      distance_from_start_km: 142,
    },
    {
      sequence: 14,
      location: "Barad",
      lat: 17.8924,
      lng: 74.5501,
      type: "Night Halt",
      distance_from_start_km: 160,
    },
    {
      sequence: 15,
      location: "Natepute",
      lat: 17.9015,
      lng: 74.7554,
      type: "Night Halt",
      distance_from_start_km: 180,
    },
    {
      sequence: 16,
      location: "Purandawade",
      lat: 17.8451,
      lng: 74.8812,
      type: "Circular Ringan",
      distance_from_start_km: 195,
    },
    {
      sequence: 17,
      location: "Malshiras / Velapur",
      lat: 17.7473,
      lng: 75.0345,
      type: "Night Halt",
      distance_from_start_km: 210,
    },
    {
      sequence: 18,
      location: "Bhandishegaon",
      lat: 17.7011,
      lng: 75.2014,
      type: "Night Halt",
      distance_from_start_km: 228,
    },
    {
      sequence: 19,
      location: "Wakhari",
      lat: 17.6891,
      lng: 75.2810,
      type: "Pre-Pandharpur Convergence",
      distance_from_start_km: 235,
    },
    {
      sequence: 20,
      location: "Pandharpur (Vitthal Temple)",
      lat: 17.6775,
      lng: 75.3283,
      type: "Final Destination",
      distance_from_start_km: 240,
    },
  ] as PalkhiWaypoint[],
};

export interface DindiMemberUnit {
  dindi_number: string;
  position: string;
  head_chief: string;
  location_origin: string;
  approx_members: number;
}

export const SANT_DNYANESHWAR_DINDI_STRUCTURE = {
  palkhi_name: "Sant Dnyaneshwar Maharaj Palkhi",
  dindi_structure: {
    front_dindis: [
      {
        dindi_number: "Dindi #27",
        position: "Front",
        head_chief: "Ha.Bha.Pa. Tambe Maharaj",
        location_origin: "Alandi",
        approx_members: 400,
      },
      {
        dindi_number: "Dindi #26",
        position: "Front",
        head_chief: "Ha.Bha.Pa. Shitre Maharaj",
        location_origin: "Pune",
        approx_members: 350,
      },
      {
        dindi_number: "Dindi #2",
        position: "Front",
        head_chief: "Ha.Bha.Pa. Uruli Kanchan Mandal",
        location_origin: "Uruli Kanchan",
        approx_members: 500,
      },
      {
        dindi_number: "Dindi #1",
        position: "Front (Leading Dindi)",
        head_chief: "Ha.Bha.Pa. Vishwasrao Sitole Deshmukh",
        location_origin: "Ankalkhop / Pune",
        approx_members: 600,
      },
    ] as DindiMemberUnit[],
    center_unit: {
      name: "Rath (Main Chariot)",
      contains: "Paduka of Sant Dnyaneshwar Maharaj",
      escort: "Bullock Cart & Horse Squad (Maulitche Ashwa)",
    },
    rear_dindis: [
      {
        dindi_number: "Dindi #1",
        position: "Rear (First behind Rath)",
        head_chief: "Ha.Bha.Pa. Vaikar Maharaj",
        location_origin: "Wai",
        approx_members: 450,
      },
      {
        dindi_number: "Dindi #2",
        position: "Rear",
        head_chief: "Ha.Bha.Pa. Chaphalakar Maharaj",
        location_origin: "Satara",
        approx_members: 300,
      },
      {
        dindi_number: "Dindi #3",
        position: "Rear",
        head_chief: "Ha.Bha.Pa. Pawar Maharaj",
        location_origin: "Saswad",
        approx_members: 350,
      },
      {
        dindi_number: "Dindi #4",
        position: "Rear",
        head_chief: "Ha.Bha.Pa. Aradkar Maharaj",
        location_origin: "Solapur",
        approx_members: 500,
      },
      {
        dindi_number: "Dindi #5",
        position: "Rear",
        head_chief: "Ha.Bha.Pa. Phaltankar Maharaj",
        location_origin: "Phaltan",
        approx_members: 400,
      },
      {
        dindi_number: "Dindi #27",
        position: "Rear (Closing Dindi)",
        head_chief: "Ha.Bha.Pa. Kurundkar Maharaj",
        location_origin: "Kolhapur",
        approx_members: 350,
      },
    ] as DindiMemberUnit[],
  },
};
